### PR TITLE
Fix mysql errors

### LINKED ISSUE #16: Threat scan - database errors
There are SQL errors related to queries in settings/ss_threat_scan.php:

```
WordPress database error Incorrect parameter count in the call to native function 'LCASE' for query ...
WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '')' at line 3 for query ...
```
[First query](https://github.com/bhadaway/stop-spammers/blob/master/settings/ss_threat_scan.php#L55-L76) contains `LCASE` function which doesn't make sense:
`LCASE(document.write(string.fromcharcode), 'script')`. It's reason why I removed this line (PR #17).

Second query - [this line](https://github.com/bhadaway/stop-spammers/blob/master/settings/ss_threat_scan.php#L285) contains non-escaped ' (it should be double escaped), so it's simple solution.

I think that PR #17 resolves all SQL errors, but it needs more testing.

### PR DESCRIPTION
**Pull request by stodorovic**
Fixes #16

### CODE REVIEW

**Comment by stodorovic** [comment]
I'm confused about notice "This feature is to be considered experimental. Use with caution and at your own risk.". I synchronized my forked repository before I push PR. Also, I see this code in master branch.

**Comment by bhadaway** [comment]
Thanks stodorovic.

I'll check it out and probably implement it in the next few days.

The message is meant to illustrate that these features aren't currently part of the core plugin yet. They're extra features that may be dated, incomplete, and not battle-tested. However, with more people testing and contributing like yourself, perhaps I can remove the warnings at some point.

**Comment by stodorovic** [comment]
I didn't explain details related to message. Content is fine and I agree with it. But somehow, this code is part of this PR. I can't figure how. You can see when you open "Files changed".

stop-spammers-notice-example

> I synchronized my forked repository before I push PR. Also, I see this code in master branch.

I'm confused because this code isn't part of my changes. Also, it already exists https://github.com/bhadaway/stop-spammers/blob/master/settings/ss_threat_scan.php#L22-L24

**Comment by bhadaway** [comment]
Yeah, that is strange. Perhaps just a GitHub glitch? Maybe a difference in encoding? Not sure.

**Comment by bhadaway** [comment]
Thanks

**Pull request merged**
